services:
  backend:
    build:
      context: ./backend
    container_name: backend_app
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend-static:/var/www/pcmaker/frontend-static:ro
      - certbot_web:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - appnet

  certbot:
    image: certbot/certbot
    container_name: certbot_service
    entrypoint: /bin/sh
    command: >
      -c "certbot certonly --webroot -w /var/www/certbot
      --email soporte@pcmaker.mx --agree-tos --no-eff-email
      --non-interactive --keep-until-expiring
      -d erp.pcmaker.mx &&
      echo '0 3 * * * certbot renew --webroot -w /var/www/certbot --quiet && nginx -s reload' > /etc/crontabs/root &&
      crond -f"
    volumes:
      - certbot_web:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    networks:
      - appnet

volumes:
  certbot_web:
  certbot_certs:

networks:
  appnet:
